version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: Build do Jekyll e deploy no Surge
          command: |
            sudo apt update
            sudo apt install -y ruby
            sudo gem install jekyll
            jekyll build
            sudo npm install -g surge
            surge _site --token $SURGE_TOKEN
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/d554cb0ee1cbf5a23ac1