version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: Build do Jekyll
          command: |
            sudo apt update
            sudo apt install ruby ruby-dev
            sudo gem install jekyll
            jekyll build
            sudo npm install -g surge
            surge _site --token $SURGE_TOKEN
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_deploy
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/d554cb0ee1cbf5a23ac1