version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: 
          name: Build do Jekyll
          command: |
            sudo gem install jekyll
            jekyll build
  upload:
    docker:
      - image: circleci/node:latest
    steps:
      - run: 
          name: Deploy no Surge
          command: |
            sudo npm install -g surge
            surge _site --token $SURGE_TOKEN
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - upload
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/d554cb0ee1cbf5a23ac1