name: Surge
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jerryjvl/jekyll-build-action@v1
      - uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'blog.rauldipeas.tk'
          project: '_site'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}