name: Surge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy no Surge
    steps:
      - uses: actions/checkout@v1
      - name: Instalação do Jekyll/Surge e deploy do site
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: gem install jekyll
      - run: npm install -g surge
      - run: jekyll build
      - run: surge _site --token ${{ secrets.SURGE_TOKEN }}
- name: Webhook
  uses: joelwmale/webhook-action@master
  env:
    WEBHOOK_URL: https://webhooks.gitter.im/e/d554cb0ee1cbf5a23ac1
    data: "{'deployment': 'finished', 'project': 'actions'}"